#!/bin/bash
#exit 0; = true
#exit 1; = false
ip="$1";
h=$(host -W 1 $ip);
r="(\.google[bot]*\.com\.|search\.msn\.com\.|\.yandex\.com\.)$"
if [[ $h =~ $r ]]; then
        d=$(echo $h | cut -f5 -d' ');
        n=$(host $d | cut -f4 -d' ');
        if [[ $n = $ip ]]; then
                #echo 0;
                exit 0;
        else
                #echo 1;
                exit 1;
        fi
else
        #echo 1;
        exit 1;
fi
